#!/bin/sh
##
## File:        $URL$
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2024 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision$
## Description: shell script to run rename X class names to template on <DIM>
##

BIN=`dirname $0`

perl $BIN/rename_tbox.pl tbox_classes

exit

