#  FASP_INSTALL_PREFIX is set here. 
if(DEFINED FASP_INSTALL_PREFIX)
    string(LENGTH "${FASP_INSTALL_PREFIX}" Z)
    if(Z)
        get_filename_component(FASP_INSTALL_PREFIX ${FASP_INSTALL_PREFIX} REALPATH)
    else(Z)
        unset(FASP_INSTALL_PREFIX)
    endif(Z)
endif(DEFINED FASP_INSTALL_PREFIX)
#
if(DEFINED FASP_INSTALL_PREFIX)
    if((EXISTS ${FASP_INSTALL_PREFIX}) AND (IS_DIRECTORY ${FASP_INSTALL_PREFIX}))
    else((EXISTS ${FASP_INSTALL_PREFIX}) AND (IS_DIRECTORY ${FASP_INSTALL_PREFIX}))
        message("-- WARNING: Cannot access installation dir=\"${FASP_INSTALL_PREFIX}\"")
        message("-- WARNING: Install to the default location \"${PROJECT_SOURCE_DIR}\"") 
    if(DEFINED CMAKE_INSTALL_PREFIX)
        set(FASP_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
    else()
        set(FASP_INSTALL_PREFIX ${PROJECT_SOURCE_DIR})
    endif()
    endif((EXISTS ${FASP_INSTALL_PREFIX})  AND  (IS_DIRECTORY ${FASP_INSTALL_PREFIX}))
else(DEFINED FASP_INSTALL_PREFIX)
    if(DEFINED CMAKE_INSTALL_PREFIX)
        set(FASP_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
    else()
        set(FASP_INSTALL_PREFIX ${PROJECT_SOURCE_DIR})
    endif()
endif(DEFINED FASP_INSTALL_PREFIX)
  
message( "-- FASP library installation dir: ${FASP_INSTALL_PREFIX}/lib")
message( "-- FASP headers installation dir: ${FASP_INSTALL_PREFIX}/include")
