/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "5.15.16"

#define QTWIDGETS_VERSION 0x050F10

#endif // QT_QTWIDGETS_VERSION_H
