#!/bin/bash

filename=$PWD
homepath="${filename%FENGSim*}"
homepath+=FENGSim
echo $homepath
cd $homepath
cd cli

LD_LIBRARY_PATH=$PWD/../toolkit/Tools/qt/icu/usr/local/lib
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/../toolkit/qt/icu/usr/local/lib
#_ORIGINAL_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/../toolkit/Tools/qt/5.12.12/plugins
export LD_LIBRARY_PATH
./../toolkit/Tools/qt/qtcreator/bin/qtcreator ./../starter/FENGSim/FENGSim.pro
