#!/bin/bash

filename=$PWD
homepath="${filename%FENGSim*}"
homepath+=FENGSim
echo $homepath

cd $homepath
git pull origin main

cd docs
git pull origin main
cd ..

cd toolkit
cd MultiX
git pull origin main
cd ..

cd CFD
git pull origin main
cd ..

cd CEM
git pull origin main
cd ..

cd DAE
git pull origin main
cd ..

cd Particles
git pull origin main
cd ..

cd NLA
git pull origin main
cd ..

cd PS
git pull origin main
cd ..

cd ..
git add docs
git add toolkit/CFD
git add toolkit/CEM
git add toolkit/DAE
git add toolkit/Particles
git add toolkit/NLA
git add toolkit/PS
git commit -m 'update all submodules'
git push origin main
