#!/bin/bash

filename=$PWD
homepath="${filename%FENGSim*}"
homepath+=FENGSim
echo $homepath
cd $homepath
cd cli

rm -rf $PWD/../toolkit/vtk/build
rm -rf $PWD/../toolkit/install/vtk_install
rm -rf $PWD/../toolkit/oce/build
rm -rf $PWD/../toolkit/install/oce_install
rm -rf $PWD/../toolkit/gmsh/build
rm -rf $PWD/../toolkit/install/gmsh_install
rm -rf $PWD/../toolkit/cgal/build
rm -rf $PWD/../toolkit/install/cgal_install
rm -rf $PWD/../toolkit/pcl/build
rm -rf $PWD/../toolkit/install/pcl_install

rm -rf $PWD/../toolkit/qt/5.12.12
rm -rf $PWD/../toolkit/qt/icu
rm -rf $PWD/../toolkit/qt/qtcreator/bin
rm -rf $PWD/../toolkit/qt/qtcreator/lib
rm -rf $PWD/../toolkit/qt/qtcreator/libexec
rm -rf $PWD/../toolkit/qt/qtcreator/share

rm -rf $PWD/../starter/build*
rm -rf $PWD/../starter/FENGSim/*.pro.user
rm -rf $PWD/../starter/ALE/build
rm -rf $PWD/../starter/CGAL/build
rm -rf $PWD/../starter/CGAL/data/output
rm -rf $PWD/../starter/GDT/build
