#!/bin/sh
# $Id: buildlist,v 1.3 2020/11/26 00:03:58 tom Exp $

: "${DIALOG=dialog}"

: "${DIALOG_OK=0}"
: "${DIALOG_CANCEL=1}"
: "${DIALOG_HELP=2}"
: "${DIALOG_EXTRA=3}"
: "${DIALOG_ITEM_HELP=4}"
: "${DIALOG_TIMEOUT=5}"
: "${DIALOG_ESC=255}"

: "${SIG_NONE=0}"
: "${SIG_HUP=1}"
: "${SIG_INT=2}"
: "${SIG_QUIT=3}"
: "${SIG_KILL=9}"
: "${SIG_TERM=15}"

tempfile=$PWD/tui_tmp.txt

$DIALOG --title "BUILDLIST DEMO" --backtitle "A user-built list" \
	--separator "|" \
	--buildlist "hello, this is a --buildlist..." 0 0 0 \
		"1" "Item number 1" "on" \
		"2" "Item number 2" "off" \
		"3" "Item number 3" "on" \
		"4" "Item number 4" "on" \
		"5" "Item number 5" "off" \
		"6" "Item number 6" "on" 2> $tempfile

returncode=$?

case "${returncode:-0}" in
  $DIALOG_OK)
    echo "Result: `cat "$tempfile"`";;
  $DIALOG_CANCEL)
    echo "Cancel pressed.";;
  $DIALOG_HELP)
    echo "Help pressed: `cat "$tempfile"`";;
  $DIALOG_EXTRA)
    echo "Extra button pressed.";;
  $DIALOG_ITEM_HELP)
    echo "Item-help button pressed: `cat "$tempfile"`";;
  $DIALOG_TIMEOUT)
    echo "Timeout expired.";;
  $DIALOG_ESC)
    if test -s "$tempfile" ; then
      cat "$tempfile"
    else
      echo "ESC pressed."
    fi
    ;;
  *)
    echo "Return code was $returncode";;
esac