set(ENABLE_MPI On CACHE BOOL "")
set(CMAKE_CXX_COMPILER "/usr/tce/packages/clang/clang-ibm-14.0.5/bin/clang++" CACHE PATH "")
set(CMAKE_C_COMPILER "/usr/tce/packages/clang/clang-ibm-14.0.5/bin/clang" CACHE PATH "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION Off CACHE BOOL "")
set(RAJA_COMPILER "RAJA_COMPILER_CLANG" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_DEBUG "-O0 -g" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -funroll-loops -finline-functions" CACHE STRING "")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g -funroll-loops -finline-functions" CACHE STRING "")
set(CMAKE_CXX_FLAGS "--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 -std=c++14 -O3 -mtune=power9  -mpower9-vector -fPIC" CACHE STRING "")
set(BLT_CXX_STD "c++14" CACHE STRING "")
set(CMAKE_CXX_STANDARD "14" CACHE STRING "")
set(CMAKE_CUDA_STANDARD "14" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_RELEASE "-O3" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_RELWITHDEBINFO "-g -lineinfo -O3" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_DEBUG "-g -G -O0" CACHE STRING "")
set(CMAKE_CUDA_FLAGS "-Xcompiler=--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1" CACHE STRING "")
set(RAJA_ENABLE_CUDA On CACHE BOOL "")
set(ENABLE_CUDA On CACHE BOOL "")
set(RAJA_ENABLE_OPENMP Off CACHE BOOL "")
set(ENABLE_OPENMP Off CACHE BOOL "")
set(ENABLE_CHAI Off CACHE BOOL "")
set(RAJA_CUDA_ARCH "sm_70" CACHE STRING "")
set(CUDA_ARCH "sm_70" CACHE STRING "")
set(ENABLE_EXAMPLES Off CACHE BOOL "")
set(ENABLE_TESTS Off CACHE BOOL "")
set(ENABLE_EXERCISES Off CACHE BOOL "")
set(RAJA_ENABLE_EXERCISES Off CACHE BOOL "")
set(RAJA_ENABLE_NESTED Off CACHE BOOL "")
set(ENABLE_CUB On CACHE BOOL "")
set(ENABLE_EXTERNAL_CUB Off CACHE BOOL "")
set(CMAKE_CUDA_COMPILER "/usr/tce/packages/cuda/cuda-11.8.0/bin/nvcc" CACHE PATH "")
set(CUDA_TOOLKIT_ROOT_DIR "/usr/tce/packages/cuda/cuda-11.8.0" CACHE PATH "")
set(BLT_CUDA_FLAGS "-Xcompiler -O3" CACHE STRING "")
set(CUDA_ARCHITECTURES "70" CACHE STRING "")
set(CMAKE_CUDA_ARCHITECTURES "70" CACHE STRING "")
set(BLT_CLANG_CUDA_ARCH "sm_70" CACHE STRING "")
set(BLT_CMAKE_IMPLICIT_LINK_DIRECTORIES_EXCLUDE "/usr/tce/packages/gcc/gcc-4.9.3/lib64;/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3;/usr/tce/packages/gcc/gcc-4.9.3/gnu/lib64;/usr/tce/packages/gcc/gcc-4.9.3/gnu/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3" CACHE STRING "")
