#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=`getApplication`

# Parse arguments
withExaCA=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    -withExaCA)
      withExaCA=true
      ;;
  esac
  shift
done

#------------------------------------------------------------------------------
# AdditiveFOAM Function Objects

# ExaCA (optional - default: false)
#export ENABLE_EXACA_DATA=true

# solidificationData (optional - default: false)
#export ENABLE_SOLIDIFICATION_DATA=true

# meltPoolDimensions (optional - default: false)
#export ENABLE_MELTPOOL_DIMENSIONS=true

# Enable ExaCA function object for '-withExaCA' flag
if [ "$withExaCA" = true ]; then
    export ENABLE_EXACA_DATA=true
fi

#------------------------------------------------------------------------------
# AdditiveFOAM
runApplication blockMesh

runApplication decomposePar

runParallel $application

runApplication reconstructPar

#------------------------------------------------------------------------------
# Reconstruct function object data
if [ "$ENABLE_EXACA_DATA" = true ]; then
    echo "x,y,z,tm,ts,cr" > ExaCA/time-temperature.csv
    tail -q -n+2 ExaCA/data_* >> ExaCA/time-temperature.csv
    rm -rf ExaCA/data_*
fi

if [ "$ENABLE_SOLIDIFICATION_DATA" = true ]; then
    echo "x,y,z,ts,cr,g,v" > solidificationData/solidification-data.csv
    tail -q -n+2 solidificationData/data_* >> solidificationData/solidification-data.csv
    rm -rf solidificationData/data_*
fi

#------------------------------------------------------------------------------
# ExaCA (Version 2.0.1)
if [ "$withExaCA" = true ]; then
    NPROCS="$(foamDictionary -expand -entry numberOfSubdomains -value system/decomposeParDict)"
    mpirun -np $NPROCS ~/install/exaca/bin/ExaCA ExaCA/input.json
fi
#------------------------------------------------------------------------------
