#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/trunk/source/scripts/source_manipulation/replaceIncludeGuards $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2024 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Description: shell script to convert 1.x codes to 2.0
##

BIN=`dirname $0`

perl $BIN/replaceIncludeGuards.pl 

exit
