#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=`getApplication`

# Parse arguments
withExaCA=false
while [ "$#" -gt 0 ]; do
  case "$1" in
    -withExaCA)
      withExaCA=true
      ;;
  esac
  shift
done

#------------------------------------------------------------------------------
# AdditiveFOAM Function Objects

# ExaCA (optional - default: false)
#export ENABLE_EXACA_DATA=true

# solidificationData (optional - default: false)
#export ENABLE_SOLIDIFICATION_DATA=true

# meltPoolDimensions (optional - default: false)
#export ENABLE_MELTPOOL_DIMENSIONS=true

# Enable ExaCA function object for '-withExaCA' flag
if [ "$withExaCA" = true ]; then
    export ENABLE_EXACA_DATA=true
fi

#------------------------------------------------------------------------------
# AdditiveFOAM
runApplication blockMesh

# Set $ADDITIVEFOAM_INST_DIR path: defaults to $WM_PROJECT_INST_DIR.
projectDir="${ADDITIVEFOAM_INST_DIR:-$WM_PROJECT_INST_DIR/AdditiveFOAM}"
path="$projectDir/applications/utilities/multiLayer"

# Create scan paths from constant/createScanPathDict
createScanPath

$path/runLayers -nLayers 2 -nCellsPerLayer 4 -layerThickness 40e-6
$path/reconstructLayers

#------------------------------------------------------------------------------
# Reconstruct function object data to layer directories
if [ "$ENABLE_EXACA_DATA" = true ]; then
    for d in layer*; do
        echo "x,y,z,tm,ts,cr" > "$d/ExaCA/time-temperature.csv"
        tail -q -n+2 "$d/ExaCA/data_"* >> "$d/ExaCA/time-temperature.csv"
        rm -rf "$d/ExaCA/data_"*
    done
fi

if [ "$ENABLE_SOLIDIFICATION_DATA" = true ]; then
    for d in layer*; do    
        echo "x,y,z,ts,cr,g,v" > "$d/solidificationData/solidification-data.csv"
        tail -q -n+2 "$d/solidificationData/data_"* >> "$d/solidificationData/solidification-data.csv"
        rm -rf "$d/solidificationData/data_"*
    done
fi

#------------------------------------------------------------------------------

# ExaCA (Version 2.0.1)
if [ "$withExaCA" = true ]; then    
    NPROCS="$(foamDictionary -expand -entry numberOfSubdomains -value system/decomposeParDict)"
    mpirun -np $NPROCS ~/install/exaca/bin/ExaCA ExaCA/input.json
fi
#------------------------------------------------------------------------------
