#!/bin/sh
# $Id: msgbox-utf8,v 1.3 2023/02/07 22:25:28 tom Exp $
# from Debian #570634

. ./setup-vars

. ./setup-utf8

$DIALOG "$@" \
	--title "ทดสอบวรรณยุกต์" \
	--msgbox "วรรณยุกต์อยู่ท้ายบรรทัดได้หรือไม่" 8 23
returncode=$?

. ./report-button
