#!/bin/sh
# $Id: password0,v 1.2 2023/02/01 00:19:12 tom Exp $

. ./setup-vars

. ./setup-tempfile

$DIALOG --insecure --passwordbox "Enter root password" 0 0 2>$tempfile

returncode=$?

. ./report-tempfile
