#!/bin/sh
# $Id: programbox3,v 1.4 2024/03/07 21:20:02 tom Exp $

. ./setup-vars

. ./setup-tempfile

ls -1 >$tempfile
(
while true
do
read text
test -z "$text" && break
ls -ld "$text" | sed -e 's%report%\\Zu\\Zr\\Z4REPORT\\Zn%g' || break
sleep 0.1
done <$tempfile
) |

$DIALOG --title "PROGRAMBOX" "$@" --color-mode 2 --programbox -1 -1

returncode=$?
. ./report-button
