#!/bin/sh
# $Id: setup-edit,v 1.4 2021/11/07 23:32:40 tom Exp $
# vile:shmode

input=`mktemp 2>/dev/null` || input=/tmp/input$$
output=`mktemp 2>/dev/null` || output=/tmp/test$$
trap "rm -f $input $output" $SIG_NONE $SIG_HUP $SIG_INT $SIG_QUIT $SIG_TERM
