#!/bin/sh
# $Id: setup-tempfile,v 1.5 2021/11/07 23:32:40 tom Exp $
# vile:shmode

tempfile=`(mktemp) 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 $SIG_NONE $SIG_HUP $SIG_INT $SIG_QUIT $SIG_TERM
