
add_library(Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin MODULE IMPORTED)


_populate_WaylandCompositor_plugin_properties(QWaylandXCompositeEglClientBufferIntegrationPlugin RELEASE "wayland-graphics-integration-server/libqt-wayland-compositor-xcomposite-egl.so" FALSE)

list(APPEND Qt5WaylandCompositor_PLUGINS Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin)
set_property(TARGET Qt5::WaylandCompositor APPEND PROPERTY QT_ALL_PLUGINS_wayland_graphics_integration_server Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin)
set_property(TARGET Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_TYPE "wayland-graphics-integration-server")
set_property(TARGET Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_EXTENDS "")
set_property(TARGET Qt5::QWaylandXCompositeEglClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_CLASS_NAME "QWaylandXCompositeEglClientBufferIntegrationPlugin")
