
add_library(Qt5::QWaylandDmabufClientBufferIntegrationPlugin MODULE IMPORTED)


_populate_WaylandCompositor_plugin_properties(QWaylandDmabufClientBufferIntegrationPlugin RELEASE "wayland-graphics-integration-server/libqt-wayland-compositor-linux-dmabuf-unstable-v1.so" FALSE)

list(APPEND Qt5WaylandCompositor_PLUGINS Qt5::QWaylandDmabufClientBufferIntegrationPlugin)
set_property(TARGET Qt5::WaylandCompositor APPEND PROPERTY QT_ALL_PLUGINS_wayland_graphics_integration_server Qt5::QWaylandDmabufClientBufferIntegrationPlugin)
set_property(TARGET Qt5::QWaylandDmabufClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_TYPE "wayland-graphics-integration-server")
set_property(TARGET Qt5::QWaylandDmabufClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_EXTENDS "")
set_property(TARGET Qt5::QWaylandDmabufClientBufferIntegrationPlugin PROPERTY QT_PLUGIN_CLASS_NAME "QWaylandDmabufClientBufferIntegrationPlugin")
