
add_library(Qt5::QWaylandEglStreamBufferIntegrationPlugin MODULE IMPORTED)


_populate_WaylandCompositor_plugin_properties(QWaylandEglStreamBufferIntegrationPlugin RELEASE "wayland-graphics-integration-server/libqt-wayland-compositor-wayland-eglstream-controller.so" FALSE)

list(APPEND Qt5WaylandCompositor_PLUGINS Qt5::QWaylandEglStreamBufferIntegrationPlugin)
set_property(TARGET Qt5::WaylandCompositor APPEND PROPERTY QT_ALL_PLUGINS_wayland_graphics_integration_server Qt5::QWaylandEglStreamBufferIntegrationPlugin)
set_property(TARGET Qt5::QWaylandEglStreamBufferIntegrationPlugin PROPERTY QT_PLUGIN_TYPE "wayland-graphics-integration-server")
set_property(TARGET Qt5::QWaylandEglStreamBufferIntegrationPlugin PROPERTY QT_PLUGIN_EXTENDS "")
set_property(TARGET Qt5::QWaylandEglStreamBufferIntegrationPlugin PROPERTY QT_PLUGIN_CLASS_NAME "QWaylandEglStreamBufferIntegrationPlugin")
