/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "5.15.16"

#define QTOPENGL_VERSION 0x050F10

#endif // QT_QTOPENGL_VERSION_H
