#!/bin/sh

mkdir build
cd build
cmake .. -DENABLE_OCC=OFF -DCMAKE_INSTALL_PREFIX=$PWD/../../install/gmsh_install -DENABLE_BUILD_DYNAMIC=ON -DENABLE_BUILD_SHARED=ON -DENABLE_BUILD_LIB=ON -DENABLE_PETSC=OFF -DENABLE_FLTK=OFF -DENABLE_MMG3D=OFF -DENABLE_MED=OFF -DENABLE_MESQUITE=OFF
make -j4
make install
