/* This file was generated by syncqt. */
#ifndef QT_QTSCXML_VERSION_H
#define QT_QTSCXML_VERSION_H

#define QTSCXML_VERSION_STR "5.15.16"

#define QTSCXML_VERSION 0x050F10

#endif // QT_QTSCXML_VERSION_H
